# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'illumi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for illumi

  # SwiftyJSON. That's great!
  pod 'SwiftyJSON'

  # Alamofire, just as elegant as requests
  pod 'Alamofire'

  # Alamofire and SwiftyJSON
  # can be used altogether with Alamofire-SwiftyJSON
  pod 'Alamofire-SwiftyJSON'

  # IQKeyboardManager
  # Totally clean, needless any line of code
  pod 'IQKeyboardManager'

  # TTGTCV, used for displaying
  # image tags
  pod "TTGTagCollectionView"

  # ImagePicker, used for
  # Image selection or something
  pod 'ImagePicker'

  target 'illumiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
